/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TP1;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author xXMAMBOXx
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoBusqueda = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        VentanaP = new javax.swing.JPanel();
        Genero = new javax.swing.JRadioButton();
        Albúm = new javax.swing.JRadioButton();
        xbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadeCanciones = new javax.swing.JList();
        Agregar = new javax.swing.JButton();
        Artista = new javax.swing.JRadioButton();
        Mimagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ncanciones = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        Nresultados = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jArtista = new javax.swing.JLabel();
        jAlbum = new javax.swing.JLabel();
        jGenero = new javax.swing.JLabel();
        jDuracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(958, 542));
        setMinimumSize(new java.awt.Dimension(958, 542));

        VentanaP.setBackground(new java.awt.Color(0, 102, 102));
        VentanaP.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        VentanaP.setForeground(new java.awt.Color(255, 255, 255));
        VentanaP.setMaximumSize(new java.awt.Dimension(958, 542));
        VentanaP.setMinimumSize(new java.awt.Dimension(958, 542));
        VentanaP.setName("i-MP3"); // NOI18N

        Genero.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Genero);
        Genero.setForeground(new java.awt.Color(255, 255, 255));
        Genero.setText("Genero");
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });

        Albúm.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Albúm);
        Albúm.setForeground(new java.awt.Color(255, 255, 255));
        Albúm.setText("Albúm");
        Albúm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbúmActionPerformed(evt);
            }
        });

        xbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        xbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbuscarActionPerformed(evt);
            }
        });

        ListadeCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListadeCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadeCancionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListadeCanciones);

        Agregar.setText("Agregar");
        Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Artista.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Artista);
        Artista.setForeground(new java.awt.Color(255, 255, 255));
        Artista.setText("Artista");
        Artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistaActionPerformed(evt);
            }
        });

        Mimagen.setText(" ");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Búsqueda :");

        Titulo.setBackground(new java.awt.Color(0, 102, 102));
        Titulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("i-MP3");

        Modificar.setText("Modificar");
        Modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Total de canciones:");

        Ncanciones.setForeground(new java.awt.Color(255, 255, 255));
        Ncanciones.setText("0");

        Result.setForeground(new java.awt.Color(255, 255, 255));
        Result.setText("Resultado(s):");

        Nresultados.setForeground(new java.awt.Color(255, 255, 255));

        jTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(240, 240, 240));
        jTitulo.setText(".");

        jArtista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jArtista.setForeground(new java.awt.Color(240, 240, 240));
        jArtista.setText(".");

        jAlbum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAlbum.setForeground(new java.awt.Color(240, 240, 240));
        jAlbum.setText(".");

        jGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jGenero.setForeground(new java.awt.Color(240, 240, 240));
        jGenero.setText(".");

        jDuracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDuracion.setForeground(new java.awt.Color(240, 240, 240));
        jDuracion.setText(".");

        javax.swing.GroupLayout VentanaPLayout = new javax.swing.GroupLayout(VentanaP);
        VentanaP.setLayout(VentanaPLayout);
        VentanaPLayout.setHorizontalGroup(
            VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaPLayout.createSequentialGroup()
                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(Mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Total)
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addComponent(Genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Artista)))
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Ncanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25))
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Albúm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addComponent(Result)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xbuscar))
                        .addGap(10, 10, 10))))
            .addGroup(VentanaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaPLayout.setVerticalGroup(
            VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(5, 5, 5)
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaPLayout.createSequentialGroup()
                                .addComponent(Mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(VentanaPLayout.createSequentialGroup()
                                .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VentanaPLayout.createSequentialGroup()
                                        .addComponent(xbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nresultados)
                                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(VentanaPLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jArtista)
                                        .addGap(18, 18, 18)
                                        .addComponent(jAlbum)))
                                .addGap(18, 18, 18)
                                .addComponent(jGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDuracion)
                                .addGap(29, 29, 29))))
                    .addGroup(VentanaPLayout.createSequentialGroup()
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Genero)
                            .addComponent(Artista)
                            .addComponent(Albúm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Total)
                            .addComponent(jLabel4)
                            .addComponent(Ncanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
          if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaGenero(xbuscar.getText());
        String total=Integer.toString(arraycanciones.getSize());
        Nresultados.setText(total);
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_GeneroActionPerformed

    private void AlbúmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbúmActionPerformed
          if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        
        int i=0;
        String nombre=null;
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaAlbum(xbuscar.getText());
        String total=Integer.toString(arraycanciones.getSize());
        Nresultados.setText(total);
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
        
        
    }//GEN-LAST:event_AlbúmActionPerformed

    private void ListadeCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadeCancionesMouseClicked
        actual.STOP();
        try {
            actual=arraycanciones.getElemento(ListadeCanciones.getAnchorSelectionIndex());
            llenardatos();
            actual.PLAY();   
        } catch (Exception ex) {}
        
            
        try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
            
        
     
    }//GEN-LAST:event_ListadeCancionesMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        JFileChooser buscar=new JFileChooser();
        FileNameExtensionFilter filtromp3= new FileNameExtensionFilter("MP3", "mp3");
        buscar.setFileFilter(filtromp3);
        String ruta;
        int seleccionado=buscar.showOpenDialog(null);
        try{
            File archivo= buscar.getSelectedFile();
            ruta= archivo.getAbsolutePath();
        }catch(Exception e){
            return;
        }
        Cancion song=new Cancion(ruta);
        Lcanciones.agregar(song);
        establecerTotal();
        if (!sonando){
            sonando=true;
            actual=song;
            llenardatos();
            llenartodos();
            actual.PLAY();
            try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
            return;
        }
        System.out.println(actual.rutaI);
        actual.STOP();
        actual=song;
        llenardatos();
        llenartodos();
        actual.PLAY();
        try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
       
        
        
        
     
    }//GEN-LAST:event_AgregarActionPerformed
    public void establecerTotal(){
        String total=Integer.toString(Lcanciones.getsize());
        Ncanciones.setText(total);
    }
    
    private void ArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistaActionPerformed
        if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaArtista(xbuscar.getText());
        String total=Integer.toString(arraycanciones.getSize());
        Nresultados.setText(total);
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_ArtistaActionPerformed

    private void xbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbuscarActionPerformed
        if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        TipoBusqueda.clearSelection();
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaCancion(xbuscar.getText());
        String total=Integer.toString(arraycanciones.getSize());
        Nresultados.setText(total);
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_xbuscarActionPerformed

    public void llenartodos(){
        Nresultados.setText("");
        int i=0;
        String nombre=null;
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray();
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
        
    } 
     
    public void llenardatos(){
        jTitulo.setText("Titulo: "+actual.getTitulo());
        jAlbum.setText("Album: "+actual.getAlbum());
        jGenero.setText("Genero: "+actual.getgenero());
        jArtista.setText("Artista: "+actual.getArtista());
        jDuracion.setText("Duracion: "+(((double) actual.getduracion())/60));
        if(actual.getImagen()!=null){
            Mimagen.setIcon(new ImageIcon(actual.getImagen()));
        }
        else{
        Mimagen.setIcon(null);
        }
    }
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                
                new NewJFrame().setVisible(true);
                
                
            }
        });
        
    }
    
    ListaCanciones Lcanciones=new ListaCanciones();
    ArrayList arraycanciones=new ArrayList(Lcanciones.getsize());
    Cancion actual;
 
    boolean sonando=false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JRadioButton Albúm;
    private javax.swing.JRadioButton Artista;
    private javax.swing.JRadioButton Genero;
    private javax.swing.JList ListadeCanciones;
    private javax.swing.JLabel Mimagen;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Ncanciones;
    private javax.swing.JLabel Nresultados;
    private javax.swing.JLabel Result;
    public static javax.swing.ButtonGroup TipoBusqueda;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Total;
    private javax.swing.JPanel VentanaP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAlbum;
    private javax.swing.JLabel jArtista;
    private javax.swing.JLabel jDuracion;
    private javax.swing.JLabel jGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JTextField xbuscar;
    // End of variables declaration//GEN-END:variables

}
