/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TP1;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author xXMAMBOXx
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoBusqueda = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Genero = new javax.swing.JRadioButton();
        Albúm = new javax.swing.JRadioButton();
        xbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadeCanciones = new javax.swing.JList();
        Agregar = new javax.swing.JButton();
        Artista = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Mimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Genero.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Genero);
        Genero.setForeground(new java.awt.Color(255, 255, 255));
        Genero.setText("Genero");
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });

        Albúm.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Albúm);
        Albúm.setForeground(new java.awt.Color(255, 255, 255));
        Albúm.setText("Albúm");
        Albúm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbúmActionPerformed(evt);
            }
        });

        xbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        xbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbuscarActionPerformed(evt);
            }
        });

        ListadeCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListadeCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadeCancionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListadeCanciones);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Artista.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(Artista);
        Artista.setForeground(new java.awt.Color(255, 255, 255));
        Artista.setText("Artista");
        Artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistaActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 102, 102));
        TipoBusqueda.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Artista");

        Mimagen.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(Mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Genero)
                                    .addComponent(Artista))
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Albúm)
                                .addGap(2, 2, 2))
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 683, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(xbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Genero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Albúm))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Artista)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(xbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addGap(215, 215, 215))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Mimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
          if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaGenero(xbuscar.getText());
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_GeneroActionPerformed

    private void AlbúmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbúmActionPerformed
          if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        
        int i=0;
        String nombre=null;
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaAlbum(xbuscar.getText());
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
        
        
    }//GEN-LAST:event_AlbúmActionPerformed

    private void ListadeCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadeCancionesMouseClicked
        actual.STOP();
        try {
            actual=arraycanciones.getElemento(ListadeCanciones.getAnchorSelectionIndex());
            actual.PLAY();   
        } catch (Exception ex) {}
        
            
        try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
            
        
     
    }//GEN-LAST:event_ListadeCancionesMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        JFileChooser buscar=new JFileChooser();
        FileNameExtensionFilter filtromp3= new FileNameExtensionFilter("MP3", "mp3");
        buscar.setFileFilter(filtromp3);
        String ruta;
        int seleccionado=buscar.showOpenDialog(null);
        try{
            File archivo= buscar.getSelectedFile();
            ruta= archivo.getAbsolutePath();
        }catch(Exception e){
            return;
        }
        Cancion song=new Cancion(ruta);
        Lcanciones.agregar(song);
        if (!sonando){
            sonando=true;
            actual=song;
            llenartodos();
            actual.PLAY();
            try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
            return;
        }
        System.out.println(actual.rutaI);
        actual.STOP();
        actual=song;
        llenartodos();
        actual.PLAY();
        try{if(actual.rutaI.equals("Desconocido")){Mimagen.setIcon(new ImageIcon(actual.rutaI));}
            }catch(Exception e){}
       
        
        
        
     
    }//GEN-LAST:event_AgregarActionPerformed

    private void ArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistaActionPerformed
        if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaArtista(xbuscar.getText());
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_ArtistaActionPerformed

    private void xbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbuscarActionPerformed
        if (xbuscar.getText().equals("")||Lcanciones.getsize()==0){
            if (Lcanciones.getsize()!=0){
                 llenartodos();    
            }
            System.out.println("si");
            return;  
        }
        TipoBusqueda.clearSelection();
        int i=0;
        String nombre=null;
        System.out.println(Lcanciones.obtenerCancion().getgenero());
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray().busquedaCancion(xbuscar.getText());
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
    }//GEN-LAST:event_xbuscarActionPerformed

    public void llenartodos(){
        int i=0;
        String nombre=null;
        DefaultListModel listac=new DefaultListModel();
        arraycanciones=Lcanciones.ListatoArray();
        while(i!=arraycanciones.getSize()){
            try {
                nombre=arraycanciones.getElemento(i++).getTitulo();
            } catch (Exception ex) {
                
            }
            listac.addElement(nombre);
        }
        
        ListadeCanciones.setModel(listac);
        
    } 
     
     
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                
                new NewJFrame().setVisible(true);
            }
        });
    }
        
    ListaCanciones Lcanciones=new ListaCanciones();
    ArrayList arraycanciones=new ArrayList(Lcanciones.getsize());
    Cancion actual;
    boolean sonando=false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JRadioButton Albúm;
    private javax.swing.JRadioButton Artista;
    private javax.swing.JRadioButton Genero;
    private javax.swing.JList ListadeCanciones;
    private javax.swing.JLabel Mimagen;
    public static javax.swing.ButtonGroup TipoBusqueda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField xbuscar;
    // End of variables declaration//GEN-END:variables
}
